#!/usr/bin/env python

"""
Copyright (C) 2024  Murdo B. Maclachlan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""


import subprocess
import sys


def str_starts_with(string: str, prefixes: list[str]):
    """
    Determines if a given string starts with any one of the given list of prefixes.

    :param string: the string to check for prefixes in
    :param prefixes: the list of prefixes
    :return: whether the string begins with any one of the prefixes
    """
    for prefix in prefixes:
        if string.startswith(prefix):
            return True
    return False


prefixes: list[str] = ["DEPRECATION", "ERROR", "WARNING", "Package", "-------"]

failed: list[str] = []
success: list[str] = []

for line in sys.stdin:

    # Don't try to install debug/error output
    if str_starts_with(line, prefixes):
        print(f"Skipping line: \"{line[:len(line)-1]}\"")  # slice removes new-line character
        continue
    
    # Installation is attempted simply by trying to install whatever comes before the first space
    # in the line, if there are any spaces
    line_parts: list[str] = line.split(" ")
    try:
        subprocess.check_call(["pip", "install", "-U", line_parts[0]])
        success.append(line_parts[0])
    except Exception as e:
        print(f"ERROR: Failed to update package: {line_parts[0]} ({e})")
        failed.append(line_parts[0])

if len(success) > 0:
    print(
        "The following packages were updated (list does not include auto-installed dependencies): "
        + ', '.join(success)
    )

if len(failed) > 0:
    print(f"Updates failed for the following packages: {', '.join(failed)}")